version: "3"

services:
  webserver:
    build:
      context: ./webserver
    ports:
      - "8877:80"
    volumes:
      - ./webserver/www:/var/www/html/
      - ./webserver/config/php/php.ini:/usr/local/etc/php/php.ini
      - ./webserver/config/vhosts:/etc/apache2/sites-enabled